# Generated by Django 2.2.6 on 2019-11-29 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_drink_dispenser', '0003_auto_20191127_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinkdispenserequest',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='drinklog',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='fooddispenserequest',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='foodlog',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
